### ISSUE TITLE
Can't convert the following type to a class yet: Archetypes.Ball.Ball_BasketBall

### ISSUE THREAD

**Issue by enzanki-ars** [jjbott/RocketLeagueReplayParser#20]
[5A04280D4A1B8713DA430D8DACFF4301.zip](https://github.com/jjbott/RocketLeagueReplayParser/files/1647540/5A04280D4A1B8713DA430D8DACFF4301.zip)

I theory, this should be the same as a normal ball right...?  If so, I should be able to create a PR for a fix.

Run via 1.9.1.  Will see if this still happens on `master` and hopefully provide a better traceback.

```
Unhandled Exception: System.NotSupportedException: Cant convert the following type to a class yet: Archetypes.Ball.Ball_BasketBall
   at RocketLeagueReplayParser.NetworkStream.ActorState.ObjectNameToClassNetCache(String objectName, IDictionary`2 classNetCacheByName)
   at RocketLeagueReplayParser.NetworkStream.ActorState.Deserialize(Int32 maxChannels, List`1 existingActorStates, List`1 frameActorStates, String[] objectIndexToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.NetworkStream.Frame.Deserialize(Int32 maxChannels, List`1& existingActorStates, String[] objectIdToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.Replay.ExtractFrames(Int32 maxChannels, IEnumerable`1 networkStream, String[] objectIdToName, IEnumerable`1 classNetCache, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion)
   at RocketLeagueReplayParser.Replay.Deserialize(BinaryReader br)
   at RocketLeagueReplayParser.Replay.Deserialize(Stream stream)
   at RocketLeagueReplayParser.Replay.Deserialize(String filePath)
   at RocketLeagueReplayParser.Console.Program.Process(Options o)
   at RocketLeagueReplayParser.Console.Program.<>c.<Main>b__0_0(Options options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at RocketLeagueReplayParser.Console.Program.Main(String[] args)
```

**Comment by jjbott** [comment]
Weird. Yeah, it's almost definitely just a regular ball. I already have
that archetype in the code but with different casing:
Archetypes.Ball.Ball_Basketball. Either they changed the casing on me, or
my test suite is missing a good basketball replay. Hmm. I can take a look
at it later today if you haven't already fixed it by then.
