### ISSUE TITLE
Unknown id isn't 0, might be lost

### ISSUE THREAD

**Issue by enzanki-ars** [jjbott/RocketLeagueReplayParser#21]
[unknown-id-not-0.zip](https://github.com/jjbott/RocketLeagueReplayParser/files/1647545/unknown-id-not-0.zip)

Not sure what is happening here...

Run via 1.9.1.  Will see if this still happens on `master` and hopefully provide a better traceback.

```
Unhandled Exception: System.Exception: Unknown id isn't 0, might be lost
   at RocketLeagueReplayParser.NetworkStream.UniqueId.DeserializeId(BitReader br, UniqueId uid, UInt32 netVersion)
   at RocketLeagueReplayParser.NetworkStream.UniqueId.Deserialize(BitReader br, UInt32 netVersion)
   at RocketLeagueReplayParser.NetworkStream.ActorStateProperty.Deserialize(IClassNetCache classMap, String typeName, String[] objectIndexToName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.NetworkStream.ActorState.Deserialize(Int32 maxChannels, List`1 existingActorStates, List`1 frameActorStates, String[] objectIndexToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.NetworkStream.Frame.Deserialize(Int32 maxChannels, List`1& existingActorStates, String[] objectIdToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.Replay.ExtractFrames(Int32 maxChannels, IEnumerable`1 networkStream, String[] objectIdToName, IEnumerable`1 classNetCache, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion)
   at RocketLeagueReplayParser.Replay.Deserialize(BinaryReader br)
   at RocketLeagueReplayParser.Replay.Deserialize(Stream stream)
   at RocketLeagueReplayParser.Replay.Deserialize(String filePath)
   at RocketLeagueReplayParser.Console.Program.Process(Options o)
   at RocketLeagueReplayParser.Console.Program.<>c.<Main>b__0_0(Options options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at RocketLeagueReplayParser.Console.Program.Main(String[] args)
```

**Comment by jjbott** [comment]
Hm, you may want to try it after disabling the check at https://github.com/jjbott/RocketLeagueReplayParser/blob/master/RocketLeagueReplayParser/NetworkStream/UniqueId.cs#L58 . You may have found a replay where that data is legitimately not 0. Either way I'll dig into it later today

**Comment by enzanki-ars** [comment]
This replay had a value of 325 based on a quick change of the line.  Commenting it out failed to parse the replay....

```
Unhandled Exception: System.Exception: "Frame" at postion 5169 has time values that are negative or suspicious. The parser got lost. Check the previous frame for bad data. Time 1.419235E-40, Delta -5.038169E-35
   at RocketLeagueReplayParser.NetworkStream.Frame.Deserialize(Int32 maxChannels, List`1& existingActorStates, String[] objectIdToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.Replay.ExtractFrames(Int32 maxChannels, IEnumerable`1 networkStream, String[] objectIdToName, IEnumerable`1 classNetCache, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion)
   at RocketLeagueReplayParser.Replay.Deserialize(BinaryReader br)
   at RocketLeagueReplayParser.Replay.Deserialize(Stream stream)
   at RocketLeagueReplayParser.Replay.Deserialize(String filePath)
   at RocketLeagueReplayParser.Console.Program.Process(Options o)
   at RocketLeagueReplayParser.Console.Program.<>c.<Main>b__0_0(Options options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at RocketLeagueReplayParser.Console.Program.Main(String[] args)
```

I just double checked, but both of these replays open correctly.

**Comment by jjbott** [comment]
Think I've got it. Some UniqueIds seem to have no data at all. Pushed new version with a fix

**Comment by enzanki-ars** [comment]
Thanks!  All of my replays parsed correctly.  I will be submitting one last minor feature request, but that should be all.   Thank you all so much for your help!

**Comment by jjbott** [comment]
No problem!
