### ISSUE TITLE
Unknown property TAGame.PRI_TA:SecondaryTitle

### ISSUE THREAD

**Issue by enzanki-ars** [jjbott/RocketLeagueReplayParser#22]
[2D00B93B4209D7F2478AD5B0D749BA2B.zip](https://github.com/jjbott/RocketLeagueReplayParser/files/1647553/2D00B93B4209D7F2478AD5B0D749BA2B.zip)

I probably can't help with this one... sorry....

Run via 1.9.1.  Will see if this still happens on `master` and hopefully provide a better traceback.

```
Unhandled Exception: System.NotSupportedException: Unknown property TAGame.PRI_TA:SecondaryTitle. Next bits in the data are 0001111101000000000000000000000000101111101000000000000000000000001001000000000000000000000000000011000000000000000000000000000000111110100000000000000000000000000101010100111111010000000000000000000000001111111010000000000000000000000001010000000000000000000000000000101000000000000000000000000000001111101000000000000000000000000001101101100000000000000000000000000000001101000111110100110010101100000000000000000000000010100011000010111001101101001110101001110101011100101000100000001001110011111111111011001110010100000000000000000011110111110011010100111010111110011010010100000000101000000100011111110101111110111000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000. Figure it out!
   at RocketLeagueReplayParser.NetworkStream.ActorStateProperty.Deserialize(IClassNetCache classMap, String typeName, String[] objectIndexToName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.NetworkStream.ActorState.Deserialize(Int32 maxChannels, List`1 existingActorStates, List`1 frameActorStates, String[] objectIndexToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.NetworkStream.Frame.Deserialize(Int32 maxChannels, List`1& existingActorStates, String[] objectIdToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.Replay.ExtractFrames(Int32 maxChannels, IEnumerable`1 networkStream, String[] objectIdToName, IEnumerable`1 classNetCache, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion)
   at RocketLeagueReplayParser.Replay.Deserialize(BinaryReader br)
   at RocketLeagueReplayParser.Replay.Deserialize(Stream stream)
   at RocketLeagueReplayParser.Replay.Deserialize(String filePath)
   at RocketLeagueReplayParser.Console.Program.Process(Options o)
   at RocketLeagueReplayParser.Console.Program.<>c.<Main>b__0_0(Options options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at RocketLeagueReplayParser.Console.Program.Main(String[] args)
```

**Comment by jjbott** [comment]
Oh man, was there a patch recently that I missed or something? :) 

I bet 4 cents that if you added a `case "TAGame.PRI_TA:SecondaryTitle":` after every `case "TAGame.PRI_TA:Title":` it'll work. I'll look into it tonight

**Comment by enzanki-ars** [comment]
Sadly, your suggestion did not work.  Seems that `SecondaryTitle` has a different length:

```
Unhandled Exception: System.Exception: "Frame" at postion 9698197 has time values that are negative or suspicious. The parser got lost. Check the previous frame for bad data. Time 5.338947E-43, Delta 1.261169E-44
   at RocketLeagueReplayParser.NetworkStream.Frame.Deserialize(Int32 maxChannels, List`1& existingActorStates, String[] objectIdToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.Replay.ExtractFrames(Int32 maxChannels, IEnumerable`1 networkStream, String[] objectIdToName, IEnumerable`1 classNetCache, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion)
   at RocketLeagueReplayParser.Replay.Deserialize(BinaryReader br)
   at RocketLeagueReplayParser.Replay.Deserialize(Stream stream)
   at RocketLeagueReplayParser.Replay.Deserialize(String filePath)
   at RocketLeagueReplayParser.Console.Program.Process(Options o)
   at RocketLeagueReplayParser.Console.Program.<>c.<Main>b__0_0(Options options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at RocketLeagueReplayParser.Console.Program.Main(String[] args)
```

In terms of the replay, it is a valid replay, but I don't see any weird titles...  Also, this replay was taken last night with many other games with the exact same players, though this one was on a different map and it was the only Rumble game of the night.  

![image](https://user-images.githubusercontent.com/8580211/35172795-18069006-fd37-11e7-9601-0ed93437dba8.png)

**Comment by jjbott** [comment]
Pushed new version with a fix
