### ISSUE TITLE
The length of the string exceeds the value set on the maxJsonLength property.

### ISSUE THREAD

**Issue by enzanki-ars** [jjbott/RocketLeagueReplayParser#23]
[maxjsonlength.zip](https://github.com/jjbott/RocketLeagueReplayParser/files/1647557/maxjsonlength.zip)

I will submit a PR for this one, but I do not like my fix...  Basically replays above about 2.1 MB are too large for the JSON export.  

Run via 1.9.1.

The following is data on some replays I have calculated using `json_export_size / replay_size`:

```
Average:   9.083
Median:    9.027
StDev:     0.533
Variance:  0.284
Min:       5.539
Max:      10.224
```

```
Unhandled Exception: System.InvalidOperationException: Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property.
   at System.Web.Script.Serialization.JavaScriptSerializer.Serialize(Object obj, StringBuilder output, SerializationFormat serializationFormat)
   at System.Web.Script.Serialization.JavaScriptSerializer.Serialize(Object obj, SerializationFormat serializationFormat)
   at System.Web.Script.Serialization.JavaScriptSerializer.SerializeValue(Object o, StringBuilder sb, Int32 depth, Hashtable objectsInUse, SerializationFormat serializationFormat, MemberInfo currentMember)
   at System.Web.Script.Serialization.JavaScriptSerializer.Serialize(Object obj, StringBuilder output, SerializationFormat serializationFormat)
   at System.Web.Script.Serialization.JavaScriptSerializer.Serialize(Object obj, SerializationFormat serializationFormat)
   at RocketLeagueReplayParser.Serializers.JsonSerializer.Serialize(Replay replay)
   at RocketLeagueReplayParser.Console.Program.Process(Options o)
   at RocketLeagueReplayParser.Console.Program.<>c.<Main>b__0_0(Options options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at RocketLeagueReplayParser.Console.Program.Main(String[] args)
```

**Comment by jjbott** [comment]
Yeah, may just have to bump the value at https://github.com/jjbott/RocketLeagueReplayParser/blob/1a697ae023265accdcb8e7ab66bdc1f2ebaa3fdf/RocketLeagueReplayParser/Serializers/JsonSerializer.cs#L43

There are definitely ways to significantly decrease the JSON size, but at the expense of readability. I may have to look into that some day.

**Comment by enzanki-ars** [comment]
I don't think it is worth reducing the size.  I really have not seen any unnecessary data in the resulting JSON.  

Also, sorry for so many incoming issues and PRs.  I ran though 107 replays, and only 7 failed, and knowing how weird and inconsistent these replays are, that is an excellent record.  Just wanted to record these issues before someone else might have stumbled on them, and hopefully save you a bit of trouble.

**Comment by enzanki-ars** [comment]
While I was looking at the fix for this issue, I noticed the `JavaScriptSerializer` at https://github.com/jjbott/RocketLeagueReplayParser/blob/1a697ae023265accdcb8e7ab66bdc1f2ebaa3fdf/RocketLeagueReplayParser/Serializers/JsonSerializer.cs#L57-L58

I noticed online that the default size limit for the  `JavaScriptSerializer` is about 2MB.  Should this one also have a `MaxJsonLength` attribute, or is it not required as the json is built differently?

**Comment by jjbott** [comment]
Yeah, SerializeRaw may not need it due to the sketchy way it is doing things. As long as an individual frame is not over 2MB it'll be ok. 

That function may need a rewrite someday, but I'm not sure anyone uses it. It's not even serializing anything exception the network stream, which isn't very good.
