### ISSUE TITLE
Undhandled exception when parsing data

### ISSUE THREAD

**Issue by Warryz** [jjbott/RocketLeagueReplayParser#38]
Hello,

I tried to parse a few of my replay files. Unfortunately everytime I try to parse a file the parser runs into an exception:
>Unhandled Exception: System.Exception: "Frame" at postion 4627 has time values that are negative or suspicious. The parser got lost. Check the previous frame for bad data. Time 4,300305E-41, Delta 7,188694E-15
   at RocketLeagueReplayParser.NetworkStream.Frame.Deserialize(Int32 maxChannels, Dictionary`2& existingActorStates, String[] objectIdToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.Replay.ExtractFrames(Int32 maxChannels, IEnumerable`1 networkStream, String[] objectIdToName, IEnumerable`1 classNetCache, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion)
   at RocketLeagueReplayParser.Replay.Deserialize(BinaryReader br)
   at RocketLeagueReplayParser.Replay.Deserialize(Stream stream)
   at RocketLeagueReplayParser.Replay.Deserialize(String filePath)
   at RocketLeagueReplayParser.Console.Program.Process(Options o)
   at RocketLeagueReplayParser.Console.Program.<>c.<Main>b__0_0(Options options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at RocketLeagueReplayParser.Console.Program.Main(String[] args)

I downloaded the latest version 1.11.0 and tried to parse my replay files from a [few](https://ballchasing.com/replay/9c391156-7007-43f2-9df7-1322444d6e7b) [days](https://ballchasing.com/replay/88d32176-a307-4d30-9b75-b7a29d998e30) ago.

**Comment by Warryz** [comment]
Hello,

thank you for your quick reply. I am going to test this new version later, when I am at home.

I looked through the documentation of Travis-CI and a [found a way to automate the upload to github release](https://docs.travis-ci.com/user/deployment/releases/). Maybe this would be a way to have the latest version available here. 

I also searched for uploading it to [nuget](https://stackoverflow.com/a/43880251).
