### ISSUE TITLE
Error during parsing : System.NotSupportedException

### ISSUE THREAD

**Issue by Ombrelin** [jjbott/RocketLeagueReplayParser#41]
Hello,

I use your library in my ASP .NET Core Web API and I encounter an error for a particular replay (see attached). The erre is the following : 

```
System.NotSupportedException: Unknown property TAGame.Car_TA:ReplicatedDemolish_CustomFX. Next bits in the data are 0111111111111111111111111111111111111010000000000000000000000000001000011000000000000000000000000000101110011000
111111111101000000000000001010111100001011111011010011000000000000110110111111010000000000000000000000000001000011000000000000000000000000000101110011000111111111101000000000000001010111100001011111011010011000000000000100011101
001000100100011000010000101110111101101111000110001011110010000000000010111100100100101101010111101001010100010001001010001001000111111011110000110111011111000010010000011110000010001011111101100110010100011111001000111101100001
010101100111011100100101010010011011111110110001100000010101100100100111110011001110011001100001100000000011111000000010101110010011100000000000000000000000000001111101000001011110010010011100001011110000110000000100010110101000
100110010110000000010110100100010111111010010111100000000111111110110001110100001101100110101111000011001111010000011010011111000000001011111001000000000010100010000000001000101001001010010111011010001100001111100110110100011000
010000101110000000111100101010001011110010000000000010111100100100111100000001110001010011111100110001001000111010010010001000110000010011110100010101000110100110001110010000010111100100011110011100111101100001101100100111011100
100011100100011011111110110001100000010101100100100111110011001110011001011110100000010111100100100101111010010010111100101000100100000000100101010101100000000111011011000100000001000010101010000001100101011101000010100011101110
100010101011100101011010110110010101011111111111101011110100100000001100010001000001011010010000011110110111110011010001100000010111100100000110111000000000111111000001011011101100100101011000000101000100010011111110011010000000
000001100111111110000001100010101000000000101000001100101000011111010000100000000000010011001101111111101111111111111001100010000000010111100000010111100100100100101011100010101010110110111101000001001111110111101010000101101011
000011010101110101110101001101111101011011110101100010111001001101100010011000000000011001111110111011000100011111111100001001101000011100111111110111000011001101001110110111011110010010010000010111100100100100110111110011100010
011001011110001010001101100110001000100111100001000110110100110000111101000101011100111000001011000010101010110101001110000011100001101100111000001110001101111001011001101011011010001001010110100000100111001100101110101110101000
001110110011011000110000100001010000100010011110011000010111100100000000000101111001001001100001100100100010100100110010101010010000001101111100010001100101110011001000100100000111011100011010101010101011001000111001100101111011
000001111110001110111001010101010000110111111101100011000000101011001001001111100110011100110010100101000000101011010111100011110100001101010001100000010110110111001110011111010000010111100100100110111100100011110100101100001100
111010000101010101100000000101001101100101111110010011100100000001010111011100010011000010000111010001101000010010100010010111100001000000000010111000100000000000111010000000000010010100110100100101110111100111001011010000000000
100110000100001001111111111010111001100010111100100000000000101111001001001111011101010111100100100001010000001010000100011010001010001100111001110010000100011110100101010011000011110111110001000111101000011111011000011100100001
110111010100000001111010111111101100011000000101011001001001111100110011100110010100100000000101001110010001100000010111100100000110101001011000011111010001011011101100100101011000000101000100010011111110111001000000000001000001
101100100001100010111011110000101000111111000010100000110000100000000000011101011000000000111111111111101110010100100110110111011000010111100000010111100100100100110001010011001010001000001010110001000111110011011010000101000110
100010101101000010010100011011110100011000100101100010101110110000100010010011010000111001111010110111100000011111111110010111101001101101010000001111000100010111001110110100000001001010011000100100100110000100001010010001001001
110000100010111100100000000000101111001001001011010111101011100100111011111110001010011011111000101010001101. Figure it out!
```

And the stack trace : 
```
 at RocketLeagueReplayParser.NetworkStream.ActorStateProperty.Deserialize(IClassNetCache classMap, String[] objectIndexToName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.NetworkStream.ActorState.Deserialize(Int32 maxChannels, IDictionary`2 existingActorStates, List`1 frameActorStates, String[] objectIndexToName, IDictionary`2 classNetCacheByName, UInt32 engineVersi
on, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.NetworkStream.Frame.Deserialize(Int32 maxChannels, Dictionary`2& existingActorStates, String[] objectIdToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt3
2 netVersion, BitReader br)
   at RocketLeagueReplayParser.Replay.ExtractFrames(Int32 maxChannels, IEnumerable`1 networkStream, String[] objectIdToName, IEnumerable`1 classNetCache, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion)
   at RocketLeagueReplayParser.Replay.Deserialize(BinaryReader br)
   at RocketLeagueReplayParser.Replay.Deserialize(Stream stream)
```

Do you have any idea of what could have gone wrong ?

Thanks in advance !

[573A977E44E556081DDF70BE5F55B5D9.zip](https://github.com/jjbott/RocketLeagueReplayParser/files/5505008/573A977E44E556081DDF70BE5F55B5D9.zip)

**Comment by jjbott** [comment]
Hi! Are you sure you're using the latest version of the library (currently 2.7.2)? I added support for that property back in June. The replay is parsing fine over here

**Comment by Ombrelin** [comment]
Thanks for your reply,

I was indeed on an older version. However I still get a different error after upgrading : 

```
System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer. (Parameter 'bytes')
   at System.Text.EncodingNLS.GetString(Byte[] bytes, Int32 index, Int32 count)
   at RocketLeagueReplayParser.BinaryReaderExtensions.ReadString2(BinaryReader br)
   at RocketLeagueReplayParser.Property.Deserialize(BinaryReader br)
   at RocketLeagueReplayParser.PropertyDictionary.Deserialize(BinaryReader br)
   at RocketLeagueReplayParser.Replay.DeserializeHeader(BinaryReader br)
   at RocketLeagueReplayParser.Replay.Deserialize(BinaryReader br)
   at RocketLeagueReplayParser.Replay.Deserialize(Stream stream)
```

If the replay is parsing fine with you I must have done something wrong. Do you have any clue about that ?

**Comment by jjbott** [comment]
Oop, sorry, I forgot about this and just noticed you closed it. Hope you were able to resolve. :)

**Comment by Ombrelin** [comment]
Yes I was the error was on my end :p thanks again for the awesome lib !
