### ISSUE TITLE
Cant convert the following type to a class yet: Archetypes.Car.Car_PostGameLobby

### ISSUE THREAD

**Issue by nerdybeast** [jjbott/RocketLeagueReplayParser#46]
Hey @jjbott ran into this exception when trying to parse a replay:
```
Cant convert the following type to a class yet: Archetypes.Car.Car_PostGameLobby

   at RocketLeagueReplayParser.NetworkStream.ActorState.ObjectNameToClassNetCache(String objectName, IDictionary`2 classNetCacheByName)
   at RocketLeagueReplayParser.NetworkStream.ActorState.Deserialize(Int32 maxChannels, IDictionary`2 existingActorStates, List`1 frameActorStates, String[] objectIndexToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.NetworkStream.Frame.Deserialize(Int32 maxChannels, Dictionary`2& existingActorStates, String[] objectIdToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.Replay.ExtractFrames(Int32 maxChannels, IEnumerable`1 networkStream, String[] objectIdToName, IEnumerable`1 classNetCache, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion)
   at RocketLeagueReplayParser.Replay.Deserialize(BinaryReader br)
   at RocketLeagueReplayParser.Replay.Deserialize(Stream stream)
   at esports_replay_review_api.Services.JsonReplayParser.GetReplayJsonAsString(IFormFile formFile) in C:\repos\personal\esports-replay-review-api\esports-replay-review-api\Services\JsonReplayParser.cs:line 242
   at esports_replay_review_api.Controllers.ReplayFileController.ReplayFileJson(ReplayRequest replayRequest) in C:\repos\personal\esports-replay-review-api\esports-replay-review-api\Controllers\ReplayFileController.cs:line 52
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
```
Not sure if this is a known issue but I figured I'd post it in here just in case.

I'm currently using version `3.2.0` of this library.

Here is link to the replay file causing this error: https://drive.google.com/drive/folders/1HV9oZZC7rtlL4cSbBla3itGcliBnNGOo?usp=sharing

**Comment by jjbott** [comment]
Thanks! I just pushed a version 3.2.1 that fixes this

**Comment by tfausak** [comment]
For posterity, this is the relevant commit: https://github.com/jjbott/RocketLeagueReplayParser/commit/1c1c2d007463d1d1c7df8c193baa578929ebcb37
