### ISSUE TITLE
Unknown property ProjectX.GRI_X:MatchGuid Issue trying to use the Console

### ISSUE THREAD

**Issue by Dominic-Emond** [jjbott/RocketLeagueReplayParser#48]
Call: .\RocketLeagueReplayParser.Console.exe 488021CA4E1F6ED79FB247A405A09E8D.replay

Response:
```
Unhandled Exception: System.NotSupportedException: Unknown property ProjectX.GRI_X:MatchGuid. Next bits in the data are 10...00. Figure it out!
   at RocketLeagueReplayParser.NetworkStream.ActorStateProperty.Deserialize(IClassNetCache classMap, String[] objectIndexToName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.NetworkStream.ActorState.Deserialize(Int32 maxChannels, IDictionary`2 existingActorStates, List`1 frameActorStates, String[] objectIndexToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.NetworkStream.Frame.Deserialize(Int32 maxChannels, Dictionary`2& existingActorStates, String[] objectIdToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, BitReader br)
   at RocketLeagueReplayParser.Replay.ExtractFrames(Int32 maxChannels, IEnumerable`1 networkStream, String[] objectIdToName, IEnumerable`1 classNetCache, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion)
   at RocketLeagueReplayParser.Replay.Deserialize(BinaryReader br)
   at RocketLeagueReplayParser.Replay.Deserialize(Stream stream)
   at RocketLeagueReplayParser.Replay.Deserialize(String filePath)
   at RocketLeagueReplayParser.Console.Program.Process(Options o)
   at RocketLeagueReplayParser.Console.Program.Main(String[] args)
```

**Comment by tfausak** [comment]
Can you upload the replay file?

**Comment by jjbott** [comment]
I bet the console version just needs updating. I'll do it after work if I don't forget again 😬

**Comment by jjbott** [comment]
I almost forgot again! Give this release a shot: https://github.com/jjbott/RocketLeagueReplayParser/releases/tag/v3.3.0

**Comment by Dominic-Emond** [comment]
Yeah I think it was just the console. I added the package directly and it worked fine!

Thanks
