### ISSUE TITLE
"Can't convert the following type to a class yet: Archetypes.GameEvent.GameEvent_FTE_Part1_Prime"

### ISSUE THREAD

**Issue by asthait** [jjbott/RocketLeagueReplayParser#50]
```
System.NotSupportedException: Cant convert the following type to a class yet: Archetypes.GameEvent.GameEvent_FTE_Part1_Prime
   at RocketLeagueReplayParser.NetworkStream.ActorState.ObjectNameToClassNetCache(String objectName, IDictionary`2 classNetCacheByName)
   at RocketLeagueReplayParser.NetworkStream.ActorState.Deserialize(Int32 maxChannels, IDictionary`2 existingActorStates, List`1 frameActorStates, String[] objectIndexToName, IDictionary`2 classNetCacheByName, UInt32 engineVersion, UInt32 licenseeVersion, UInt32 netVersion, UInt32 changelist, BitReader br)
```

Replay file link that gives parsing error : [0AE90A0B45C73A5A7B843990EF4572C1.replay](https://drive.google.com/file/d/1d72AztbXqplrPmytlfHISSLpZI97rn6U/view?usp=share_link)

**Comment by jjbott** [comment]
Thanks! I just pushed a new version (V3.4.2) of the library that seems to fix it, but I've only verified against this one replay. I'll be keeping an eye out for others

**Comment by asthait** [comment]
Thanks for your response. Its working now for the specified replay file. I will let you know if any issues find further.
