### ISSUE TITLE
Can't serialize new mutator demo

### ISSUE THREAD

**Issue by phillijw** [jjbott/RocketLeagueReplayParser#7]
The mutation in the demo was that the ball was smaller than normal and a little bit bouncier I think. See http://www.rocketleaguereplays.com/replays/2713/

<pre>
Test Name:	TestDeserialization("C:\\Users\\Joe\\Documents\\My Games\\Rocket League\\TAGame\\Demos\\small bouncy ball-BAFBCDFF475F53B123ED05A5A06AB9ED.replay")
Test FullName:	RocketLeagueReplayParser.Tests.DeserializeTests.TestDeserialization("C:\\Users\\Joe\\Documents\\My Games\\Rocket League\\TAGame\\Demos\\small bouncy ball-BAFBCDFF475F53B123ED05A5A06AB9ED.replay")
Test Source:	C:\repos\RocketLeagueReplayParser\RocketLeagueReplayParser.Tests\DeserializeTests.cs : line 25
Test Outcome:	Failed
Test Duration:	0:00:00.118

Result StackTrace:	
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
at RocketLeagueReplayParser.NetworkStream.ActorState.Deserialize(List`1 existingActorStates, List`1 frameActorStates, IDictionary`2 objectIndexToName, IEnumerable`1 classNetCache, BitReader br) in C:\repos\RocketLeagueReplayParser\RocketLeagueReplayParser\NetworkStream\ActorState.cs:line 139
at RocketLeagueReplayParser.NetworkStream.Frame.Deserialize(List`1& existingActorStates, IDictionary`2 objectIdToName, IEnumerable`1 classNetCache, BitReader br) in C:\repos\RocketLeagueReplayParser\RocketLeagueReplayParser\NetworkStream\Frame.cs:line 39
at RocketLeagueReplayParser.Replay.ExtractFrames(IEnumerable`1 networkStream, IEnumerable`1 keyFramePositions, IDictionary`2 objectIdToName, IEnumerable`1 classNetCache, StringBuilder logSb) in C:\repos\RocketLeagueReplayParser\RocketLeagueReplayParser\Replay.cs:line 172
at RocketLeagueReplayParser.Replay.Deserialize(BinaryReader br, String& log) in C:\repos\RocketLeagueReplayParser\RocketLeagueReplayParser\Replay.cs:line 139
at RocketLeagueReplayParser.Replay.Deserialize(String filePath, String& log) in C:\repos\RocketLeagueReplayParser\RocketLeagueReplayParser\Replay.cs:line 19
at RocketLeagueReplayParser.Tests.DeserializeTests.TestDeserialization(String filePath) in C:\repos\RocketLeagueReplayParser\RocketLeagueReplayParser.Tests\DeserializeTests.cs:line 27
Result Message:	System.InvalidOperationException : Sequence contains no elements
</pre>

**Comment by jjbott** [comment]
Oh, you assigned this to yourself. Uh. Good luck. :)
